---
version: "2"

plugins:
  csslint:
    enabled: true
  duplication:
    enabled: true
  fixme:
    enabled: true
  markdownlint:
    enabled: true
  shellcheck:
    enabled: true

exclude_patterns:
  - "**.txt"
  - "**.json"
  - "**/api/"
  - "**/build/"
  - "**/coverage/"
  - "**/dist/"
  - "**/node_modules/"
  - "**/public/"
  - client/config/
  - servers/lib/src/types.ts
