---
version: "2"

plugins:
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        typescript:
        javascript:
        python:
          python_version: 3
  eslint:
    enabled: true
    channel: "eslint-8"
  fixme:
    enabled: true
  markdownlint:
    enabled: true
    checks:
      MD013:
        enabled: true
        line_length: 30
  shellcheck:
    enabled: true

exclude_patterns:
  - "**.txt"
  - "**.json"
  - "**/api/"
  - "**/build/"
  - "**/coverage/"
  - "**/dist/"
  - "**/node_modules/"
  - "**/public/"
  - client/config/
  - servers/lib/src/types.ts
